from .candidate_prompt import CANDIDATE_GENERATION_PROMPT
from .extraction_prompt import CHINESE_EXTRACTION_SYSTEM_PROMPT, EXTRACTION_SYSTEM_PROMPT
from .memory_prompt import MEMORY_BUILDER_PROMPT

__all__ = [
    "CANDIDATE_GENERATION_PROMPT",
    "CHINESE_EXTRACTION_SYSTEM_PROMPT",
    "EXTRACTION_SYSTEM_PROMPT",
    "MEMORY_BUILDER_PROMPT",
]
